# Generated by Django 2.2.8 on 2021-01-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kasir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaMenu', models.CharField(max_length=255)),
                ('hargaMenu', models.CharField(max_length=255)),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
