# Generated by Django 2.2.8 on 2021-01-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0002_makanan_minuman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kasir',
        ),
    ]
