# Generated by Django 2.2.8 on 2021-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0003_delete_kasir'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='imageMakanan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
