# Generated by Django 2.2.8 on 2021-01-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0005_auto_20210122_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='imageMakanan',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
    ]
