# Generated by Django 2.2.8 on 2021-01-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0006_auto_20210122_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuman',
            name='imageMinuman',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
    ]
