# Generated by Django 2.2.8 on 2021-01-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0007_minuman_imageminuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuman',
            name='imageMinuman',
            field=models.ImageField(blank=True, null=True, upload_to='img/menu/'),
        ),
    ]
