# Generated by Django 2.2.8 on 2021-05-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0008_auto_20210123_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuman',
            name='imageMinuman',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
    ]
